<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Visus.Cuid.Benchmarks</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1515;CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\cuid.net\cuid.net.csproj"/>
  </ItemGroup>

</Project>
