name: Release

on:
  workflow_dispatch:
  tags:
    - '*'
        
jobs:
  build:
    name: Build, Analyze & Test
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os}}-nuget     
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json          
      - name: Restore
        run: dotnet restore --verbosity Quiet
      - name: Build
        run: dotnet build -c release --no-restore 


          